#!/bin/sh -e

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Dx11-backend=enabled \
    -Dxwayland=enabled \
    -Drenderers=gles2 \
    . build

ninja -C build
ninja -C build install
