#!/bin/sh

./configure \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-inotify \
    --enable-user-session \
    --with-dbus-user=dbus \
    --disable-systemd \
    --disable-asserts \
    --prefix=/usr \
    --without-x \
    --with-system-socket=/run/dbus/system_bus_socket \
    --disable-doxygen-docs \
    --with-system-pid-file=/run/dbus/pid \
    --with-console-auth-dir=/run/console

make
make DESTDIR="$1" install

# Install service.
install -Dm755 dbus.run "$1/etc/sv/dbus/run"
install -Dm755 dbus.check "$1/etc/sv/dbus/check"
ln -s /run/runit/supervise.dbus "$1/etc/sv/dbus/supervise"
