#!/bin/sh -e


bmake \
	WITH_POSIX_C_SOURCE=YES \
	WITH_XWAYLAND=YES \
	WITH_SCREENCOPY=YES \
	WITH_GAMMACONTROL=YES \
	WITH_LAYERSHELL=YES \
	ETC_PREFIX= \


mkdir -p $1/etc/hikari
mkdir -p $1/etc/pam.d

cp etc/hikari/* $1/etc/hikari
cp etc/pam.d/hikari-unlocker.Linux $1/etc/pam.d/hikari-unlocker

bmake PREFIX=/usr install
